FROM maven:3.9.0-eclipse-temurin-17 as builder

WORKDIR /app

COPY backend/pom.xml .
RUN mvn dependency:go-offline

COPY backend/src ./src
RUN mvn clean package -DskipTests

FROM eclipse-temurin:17-jre-alpine

WORKDIR /app

COPY --from=builder /app/target/app.jar ./app.jar

EXPOSE 8080

CMD ["java", "-jar", "app.jar"]
