FROM node:20-alpine as builder

WORKDIR /app

COPY frontend/package*.json ./
# use npm install since package-lock.json isn't checked in
RUN npm install

COPY frontend . 
RUN npm run build

FROM node:20-alpine

WORKDIR /app

# Installer serve localement
COPY frontend/package*.json ./
RUN npm install serve

COPY --from=builder /app/dist ./dist

EXPOSE 3000

CMD ["npx", "serve", "-s", "dist", "-l", "3000"]
